apiVersion: v1         
kind: ConfigMap            
metadata:            
  name: eph-ephemerup-config                                        
  namespace: "eph"             
  labels:                      
    app.kubernetes.io/name: ephemerup                               
    helm.sh/chart: ephemerup-1.0.0     
    app.kubernetes.io/instance: eph                                                                                                     
    app.kubernetes.io/managed-by: Helm                              
  annotations:                                                      
    app: ephemerup              
data:                                                                                                                                   
  listen = "8080"     
  bodylimit = "1024"                                                
  super = "root"                                                    
  mail = {                                                                                                                              
    server =                                                                                                                            
    port =                                                          
    from =            
    password =                                                      
  }                                                                 
  apicontexts = [                                                                                                                       
  ]  
